version: '3.8'

services:
  fb-scraper:
    build: .
    container_name: fb-scraper
    restart: unless-stopped
    environment:
      - INTERNAL_API_SECRET=b137e9844590984a3bbabdbe86e19d3d8378232a09c81523b6e68ff3ae5d7f37
    shm_size: '2gb'
    volumes:
      - ./logs:/app/logs
      - ./debug_screenshots:/app/debug_screenshots
